// <auto-generated />
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231030201159_Contacts")]
    partial class Contacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Data.Contacts", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_calculated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_of_residence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date_of_birth_date_picker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("do_you_speak_english_")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender__")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hs_language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobilephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spiritual_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("verified_aky_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("verified_art_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("verified_knowledge_teachers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("verified_music")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("verified_rituals_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("verified_yoga_and_meditation_teachers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ContactsList");
                });
#pragma warning restore 612, 618
        }
    }
}
