// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Data.AllContactsList", b =>
                {
                    b.Property<string>("AdditionalEmailAddresses")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("additional_email_addresses");

                    b.Property<DateOnly?>("AgreedDateOfInitiationWithYourSwamiRishi")
                        .HasColumnType("date")
                        .HasColumnName("agreed_date_of_initiation_with_your_swami_rishi");

                    b.Property<string>("AkyTeacherCalculated")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aky_teacher_calculated");

                    b.Property<string>("AkyTeacherCalculatedLabel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aky_teacher_calculated_label");

                    b.Property<string>("AkyTeachersCountriesUnderTheirResponsibility")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("aky_teachers___countries_under_their__responsibility");

                    b.Property<bool?>("AreYouABrahmachariBrahmachariniRadio")
                        .HasColumnType("bit")
                        .HasColumnName("are_you_a_brahmachari___brahmacharini___radio_");

                    b.Property<bool?>("AreYouAvailableToDoSeva")
                        .HasColumnType("bit")
                        .HasColumnName("are_you_available_to_do_seva");

                    b.Property<string>("AreYouInitiatedInAtmaKriyaYoga")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("are_you_initiated_in_atma_kriya_yoga_");

                    b.Property<string>("AtmaKriyaWhatYearWereYouInitiated")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_what_year_were_you_initiated_");

                    b.Property<string>("AtmaKriyaYogaTeacherAlbania")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_albania");

                    b.Property<string>("AtmaKriyaYogaTeacherArgentina")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_argentina");

                    b.Property<string>("AtmaKriyaYogaTeacherAustralia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_australia");

                    b.Property<string>("AtmaKriyaYogaTeacherAustria")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_austria");

                    b.Property<string>("AtmaKriyaYogaTeacherBelgium")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_belgium");

                    b.Property<string>("AtmaKriyaYogaTeacherBolivia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_bolivia");

                    b.Property<string>("AtmaKriyaYogaTeacherBosniaAndHerzegovina")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_bosnia_and_herzegovina");

                    b.Property<string>("AtmaKriyaYogaTeacherBrazil")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_brazil");

                    b.Property<string>("AtmaKriyaYogaTeacherBulgaria")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_bulgaria");

                    b.Property<string>("AtmaKriyaYogaTeacherCambodia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_cambodia");

                    b.Property<string>("AtmaKriyaYogaTeacherCanada")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_canada");

                    b.Property<string>("AtmaKriyaYogaTeacherChile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_chile");

                    b.Property<string>("AtmaKriyaYogaTeacherChina")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_china");

                    b.Property<string>("AtmaKriyaYogaTeacherColombia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_colombia");

                    b.Property<string>("AtmaKriyaYogaTeacherCoteDIvoire")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_cote_d_ivoire");

                    b.Property<string>("AtmaKriyaYogaTeacherCroatia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_croatia");

                    b.Property<string>("AtmaKriyaYogaTeacherCzechRepublic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_czech_republic");

                    b.Property<string>("AtmaKriyaYogaTeacherDenmark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_denmark");

                    b.Property<string>("AtmaKriyaYogaTeacherEcuador")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_ecuador");

                    b.Property<string>("AtmaKriyaYogaTeacherEgypt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_egypt");

                    b.Property<string>("AtmaKriyaYogaTeacherEstonia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_estonia");

                    b.Property<string>("AtmaKriyaYogaTeacherFinland")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_finland");

                    b.Property<string>("AtmaKriyaYogaTeacherFrance")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_france");

                    b.Property<string>("AtmaKriyaYogaTeacherGermany")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_germany");

                    b.Property<string>("AtmaKriyaYogaTeacherGreece")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_greece");

                    b.Property<string>("AtmaKriyaYogaTeacherHungary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_hungary");

                    b.Property<string>("AtmaKriyaYogaTeacherIndia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_india");

                    b.Property<string>("AtmaKriyaYogaTeacherIndonesia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_indonesia");

                    b.Property<string>("AtmaKriyaYogaTeacherIreland")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_ireland");

                    b.Property<string>("AtmaKriyaYogaTeacherItaly")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_italy");

                    b.Property<string>("AtmaKriyaYogaTeacherJapan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_japan");

                    b.Property<string>("AtmaKriyaYogaTeacherJordan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_jordan");

                    b.Property<string>("AtmaKriyaYogaTeacherKenya")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_kenya");

                    b.Property<string>("AtmaKriyaYogaTeacherLatvia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_latvia");

                    b.Property<string>("AtmaKriyaYogaTeacherLebanon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_lebanon");

                    b.Property<string>("AtmaKriyaYogaTeacherLithuania")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_lithuania");

                    b.Property<string>("AtmaKriyaYogaTeacherMacedonia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_macedonia");

                    b.Property<string>("AtmaKriyaYogaTeacherMadagascar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_madagascar");

                    b.Property<string>("AtmaKriyaYogaTeacherMalaysia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_malaysia");

                    b.Property<string>("AtmaKriyaYogaTeacherMauritius")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_mauritius");

                    b.Property<string>("AtmaKriyaYogaTeacherMexico")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_mexico");

                    b.Property<string>("AtmaKriyaYogaTeacherMontenegro")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_montenegro");

                    b.Property<string>("AtmaKriyaYogaTeacherMozambique")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_mozambique");

                    b.Property<string>("AtmaKriyaYogaTeacherNepal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_nepal");

                    b.Property<string>("AtmaKriyaYogaTeacherNetherlands")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_netherlands");

                    b.Property<string>("AtmaKriyaYogaTeacherNewZealand")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_new_zealand");

                    b.Property<string>("AtmaKriyaYogaTeacherNorway")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_norway");

                    b.Property<string>("AtmaKriyaYogaTeacherPeru")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_peru");

                    b.Property<string>("AtmaKriyaYogaTeacherPoland")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_poland");

                    b.Property<string>("AtmaKriyaYogaTeacherPortugal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_portugal");

                    b.Property<string>("AtmaKriyaYogaTeacherReunion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_reunion");

                    b.Property<string>("AtmaKriyaYogaTeacherRomania")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_romania");

                    b.Property<string>("AtmaKriyaYogaTeacherRussia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_russia");

                    b.Property<string>("AtmaKriyaYogaTeacherSerbia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_serbia");

                    b.Property<string>("AtmaKriyaYogaTeacherSingapore")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_singapore");

                    b.Property<string>("AtmaKriyaYogaTeacherSlovakia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_slovakia");

                    b.Property<string>("AtmaKriyaYogaTeacherSlovenia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_slovenia");

                    b.Property<string>("AtmaKriyaYogaTeacherSouthAfrica")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_south_africa");

                    b.Property<string>("AtmaKriyaYogaTeacherSpain")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_spain");

                    b.Property<string>("AtmaKriyaYogaTeacherSpn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_spn");

                    b.Property<string>("AtmaKriyaYogaTeacherSwaziland")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_swaziland");

                    b.Property<string>("AtmaKriyaYogaTeacherSwitzerland")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_switzerland");

                    b.Property<string>("AtmaKriyaYogaTeacherTaiwan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_taiwan");

                    b.Property<string>("AtmaKriyaYogaTeacherTurkey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_turkey");

                    b.Property<string>("AtmaKriyaYogaTeacherUkraine")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_ukraine");

                    b.Property<string>("AtmaKriyaYogaTeacherUnitedArabEmirates")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_united_arab_emirates");

                    b.Property<string>("AtmaKriyaYogaTeacherUnitedKingdom")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_united_kingdom");

                    b.Property<string>("AtmaKriyaYogaTeacherUnitedStates")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_united_states");

                    b.Property<string>("AtmaKriyaYogaTeacherUruguay")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("atma_kriya_yoga_teacher_uruguay");

                    b.Property<string>("BecomeADevoteeStatus")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("become_a_devotee_status");

                    b.Property<string>("BecomeAOmcCoordinateurStatus")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("become_a_omc_coordinateur_status");

                    b.Property<string>("BecomeAnAtmaKriyaYogaStudentStatus")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("become_an_atma_kriya_yoga_student_status");

                    b.Property<string>("BrahmachariWhatYearWereYouInitiated")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("brahmachari___what_year_were_you_initiated_");

                    b.Property<string>("City")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("city");

                    b.Property<string>("CitySOrVillageSWhereYouWillOrganizeOmChantingCircles")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city_s__or_village_s__where_you_will_organize_om_chanting_circles");

                    b.Property<string>("CommentOmcStudent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment_omc_student");

                    b.Property<string>("CommentOmcTeacher")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment_omc_teacher");

                    b.Property<string>("CommentStudent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment_student");

                    b.Property<string>("CommentTeacher")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment_teacher");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comments");

                    b.Property<string>("CompletedDevoteeCourse")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("completed_devotee_course");

                    b.Property<bool?>("Consent")
                        .HasColumnType("bit")
                        .HasColumnName("consent_");

                    b.Property<string>("Consent1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("consent_1");

                    b.Property<string>("ConsentBecomeADevoteeDataSharing")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("consent_become_a_devotee___data_sharing");

                    b.Property<bool?>("ConsentCollectAndProcessMyDataToInsertThisDataIntoOurDatabase")
                        .HasColumnType("bit")
                        .HasColumnName("consent_collect_and_process_my_data_to_insert_this_data_into_our_database");

                    b.Property<string>("ConsentFindAnAtmaKriyaYogaTeacher")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("consent___find_an_atma_kriya_yoga_teacher");

                    b.Property<bool?>("ConsentForTheTrainingOfOmChantingOrganisersForMySpiritualNameToBeGiven")
                        .HasColumnType("bit")
                        .HasColumnName("consent_for_the_training_of__om_chanting_organisers__for_my_spiritual_name_to_be_given");

                    b.Property<string>("ConsentTransferDataToBmicAndOmChantingCoordinators")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("consent_transfer_data_to_bmic_and_om_chanting_coordinators");

                    b.Property<string>("ContactStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_status");

                    b.Property<string>("CountryAtmaKriyaYoga")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country_atma_kriya_yoga");

                    b.Property<string>("CountryCalculated")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("country_calculated");

                    b.Property<string>("CountryOfResidence")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country_of_residence");

                    b.Property<DateOnly?>("DateAtmaKriyaYogaCourse")
                        .HasColumnType("date")
                        .HasColumnName("date_atma_kriya_yoga_course");

                    b.Property<DateOnly?>("DateBlessingOmc")
                        .HasColumnType("date")
                        .HasColumnName("date_blessing_omc");

                    b.Property<DateOnly?>("DateOfBirthDatePicker")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth_date_picker");

                    b.Property<DateOnly?>("DateRequestBecomeADevotee")
                        .HasColumnType("date")
                        .HasColumnName("date_request___become_a_devotee");

                    b.Property<DateOnly?>("DateRequestBecomeAnAtmaKriyaYogaStudent")
                        .HasColumnType("date")
                        .HasColumnName("date_request_become_an_atma_kriya_yoga_student");

                    b.Property<string>("DateRequestOmcBlessing")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("date_request___omc_blessing");

                    b.Property<bool?>("DevoteeApprovedByTheResponsibleSwamiNi")
                        .HasColumnType("bit")
                        .HasColumnName("devotee_approved_by_the_responsible_swami_ni");

                    b.Property<string>("DoYouAlreadyHaveAPotentialGroupOfParticipants")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("do_you_already_have_a_potential_group_of_participants_");

                    b.Property<string>("DoYouHaveACopyOfAnyOfTheFollowingBooks")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("do_you_have_a_copy_of_any_of_the_following_books_");

                    b.Property<string>("DoYouHaveASevaRoleForBmInYourCountry")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("do_you_have_a_seva_role_for_bm_in_your_country_");

                    b.Property<bool?>("DoYouSpeakEnglish")
                        .HasColumnType("bit")
                        .HasColumnName("do_you_speak_english_");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("firstname");

                    b.Property<string>("GdprConsentForSwamiBmccCommunication")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)")
                        .HasColumnName("gdpr___consent_for_swami_bmcc_communication");

                    b.Property<string>("Gender")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("gender__");

                    b.Property<string>("Gender1")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("gender");

                    b.Property<bool?>("GformAreYouABhaktiMargaTeacher")
                        .HasColumnType("bit")
                        .HasColumnName("gform___are_you_a_bhakti_marga_teacher_");

                    b.Property<string>("HasFilledTheDevoteeApplicationForm")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("has_filled_the_devotee_application_form");

                    b.Property<string>("HaveYouDoneTheAtmaKriyaYogaCourse")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("have_you_done_the_atma_kriya_yoga_course_");

                    b.Property<string>("HaveYouTakenStudyTheDevoteeCourse")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("have_you_taken_study_the_devotee_course");

                    b.Property<string>("HaveYouTakenTheOmChantingWorkshop")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("have_you_taken_the_om_chanting_workshop_");

                    b.Property<string>("HowManyOmChantingCirclesHaveYouParticipatedIn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("how_many_om_chanting_circles_have_you_participated_in_");

                    b.Property<string>("HsLanguage")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)")
                        .HasColumnName("hs_language");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool?>("InitiatedDevoteeOfParamahamsaVishwandaYNRadio")
                        .HasColumnType("bit")
                        .HasColumnName("initiated_devotee_of_paramahamsa_vishwanda_y_n__radio_");

                    b.Property<string>("IshtaDev")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ishta_dev");

                    b.Property<DateOnly?>("LastCourseCompletedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_course_completed_date");

                    b.Property<string>("Lastname")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("lastname");

                    b.Property<string>("MergedDataHubConsents")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("merged_data_hub_consents");

                    b.Property<string>("Mobilephone")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("mobilephone");

                    b.Property<string>("NameAndContactOfTheOmcTeacher")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name_and_contact_of_the_omc_teacher");

                    b.Property<string>("Nationality")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("nationality_");

                    b.Property<string>("NotBlessedStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("not_blessed_status");

                    b.Property<string>("NotesForSwamiBecomeADevotee")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes_for_swami___become_a_devotee");

                    b.Property<string>("OmcAcCountriesUnderTheirResponsibility")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("omc_ac___countries_under_their__responsibility");

                    b.Property<string>("OtherSkillsAndQualitiesYouCouldOfferAsSevaForBhaktiMargaInYourCountry")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("other_skills_and_qualities_you_could_offer_as_seva_for_bhakti_marga_in_your_country_");

                    b.Property<string>("PaymentAtmaKriyaYogaCourse")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("payment_atma_kriya_yoga_course");

                    b.Property<string>("Phone")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("phone");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("picture");

                    b.Property<bool?>("PreferedSwamiRishi")
                        .HasColumnType("bit")
                        .HasColumnName("prefered_swami_rishi");

                    b.Property<string>("Profession")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("profession");

                    b.Property<string>("QuitDevoteeDate")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("quit_devotee_date");

                    b.Property<string>("QuitDevoteeStatus")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("quit_devotee_status");

                    b.Property<string>("Read")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("read");

                    b.Property<string>("Role")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("role");

                    b.Property<bool?>("Shaktipat")
                        .HasColumnType("bit")
                        .HasColumnName("shaktipat");

                    b.Property<DateOnly?>("SinceHowLongYouFollowTheTeachingsOfPv")
                        .HasColumnType("date")
                        .HasColumnName("since_how_long_you_follow_the_teachings__of_pv");

                    b.Property<string>("SpiritualName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("spiritual_name");

                    b.Property<string>("State")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("state");

                    b.Property<string>("SwamiCountriesUnderTheirResponsability")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("swami___countries_under_their__responsability");

                    b.Property<string>("TeacherArt")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("teacher___art");

                    b.Property<string>("TeacherKnowledge")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("teacher___knowledge");

                    b.Property<string>("TeacherMusic")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("teacher___music");

                    b.Property<string>("TeacherRituals")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("teacher___rituals");

                    b.Property<string>("TeacherYogaMeditation")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("teacher___yoga___meditation");

                    b.Property<string>("TransferDataToResponsibleCountrySwami")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("transfer_data_to_responsible_country_swami");

                    b.Property<string>("VerifiedArtTeacher")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("verified_art_teacher");

                    b.Property<string>("VerifiedKnowledgeTeachers")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("verified_knowledge_teachers");

                    b.Property<string>("VerifiedMusic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("verified_music");

                    b.Property<string>("VerifiedRitualsTeacher")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("verified_rituals_teacher");

                    b.Property<string>("VerifiedTeachers")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("verified_teachers");

                    b.Property<string>("VerifiedYogaAndMeditationTeachers")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("verified_yoga_and_meditation_teachers");

                    b.Property<string>("WhatAreTheSkillsAndQualitiesYouCouldOffer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("what_are_the_skills_and_qualities_you_could_offer_");

                    b.Property<string>("WhatIsYourBhaktiMargaRoleInYourCountry")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("what_is_your_bhakti_marga_role_in_your_country");

                    b.Property<string>("WhatLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("what_level_");

                    b.Property<string>("WhatRoleDoYouHaveInBhaktiMarga")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("what_role_do_you_have_in_bhakti_marga_");

                    b.Property<DateTime?>("WhatYearWereYouInitiated")
                        .HasColumnType("datetime2")
                        .HasColumnName("what_year_were_you_initiated_");

                    b.Property<string>("WhoDoYouWantInitiatedYouAsDevotee")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("who_do_you_want_initiated_you_as_devotee_");

                    b.Property<string>("WhoInitiatedYouBrahmachariBrahmachariniDropdown")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("who_initiated_you__brahmachari_brahmacharini__dropdown_");

                    b.Property<string>("WhoInitiatedYouSwami")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("who_initiated_you__swami");

                    b.Property<string>("WhyWouldYouLikeToOrganizeOmChantingGroupS")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("why_would_you_like_to_organize_om_chanting_group_s__");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("zip");

                    b.ToTable("allContactsList", (string)null);
                });

            modelBuilder.Entity("DataAccess.Data.Contacts", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double?>("SharingBMInt")
                        .HasColumnType("float");

                    b.Property<double?>("SharingCountry")
                        .HasColumnType("float");

                    b.Property<double?>("SharingTeachers")
                        .HasColumnType("float");

                    b.Property<int?>("TotalCourses")
                        .HasColumnType("int");

                    b.Property<double?>("TotalFees")
                        .HasColumnType("float");

                    b.Property<double?>("TotalIncome")
                        .HasColumnType("float");

                    b.Property<int?>("TotalStudents")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_calculated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_of_residence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date_of_birth_date_picker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("do_you_speak_english_")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender__")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hs_language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobilephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spiritual_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("verified_aky_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("verified_art_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("verified_knowledge_teachers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("verified_music")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("verified_rituals_teacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("verified_yoga_and_meditation_teachers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ContactsList");
                });

            modelBuilder.Entity("DataAccess.Data.Courses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DateTimeAdded")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("FeesAmount")
                        .HasColumnType("float");

                    b.Property<int?>("IdTeacher")
                        .HasColumnType("int");

                    b.Property<long?>("LineItemId")
                        .HasColumnType("bigint");

                    b.Property<double?>("LineItemPrice")
                        .HasColumnType("float");

                    b.Property<string>("LineItemTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Paid")
                        .HasColumnType("bit");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Quantity")
                        .HasColumnType("tinyint");

                    b.Property<string>("Refunded")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalesChannel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Store")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("consent")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("newcomer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CoursesList");
                });

            modelBuilder.Entity("DataAccess.Data.Fees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdTeacher")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Paid")
                        .HasColumnType("bit");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Validate")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FeesList");
                });

            modelBuilder.Entity("DataAccess.Data.ReceiptImage", b =>
                {
                    b.Property<int>("IdKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKey"));

                    b.Property<int?>("FeeId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKey");

                    b.HasIndex("FeeId");

                    b.ToTable("ReceiptImagesList");
                });

            modelBuilder.Entity("DataAccess.Data.ReceiptImage", b =>
                {
                    b.HasOne("DataAccess.Data.Fees", "ContactsFeesList")
                        .WithMany("FeesReceipt")
                        .HasForeignKey("FeeId");

                    b.Navigation("ContactsFeesList");
                });

            modelBuilder.Entity("DataAccess.Data.Fees", b =>
                {
                    b.Navigation("FeesReceipt");
                });
#pragma warning restore 612, 618
        }
    }
}
